CREATE TABLE SOA_INT_LOGS (
	LOG_ID INT NOT NULL AUTO_INCREMENT,
	TEXT VARCHAR(250) NOT NULL,
	TYPE_TEXT VARCHAR(30) NOT NULL,
	LOG_DATE TIMESTAMP NOT NULL,
	CONSTRAINT SOA_INT_LOGS PRIMARY KEY (LOG_ID)
);
